### ISSUE TITLE
Should we limit the number of recycler delete requests?

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-recycler#1]
I like how this plugin mimics our local changes delete user interface.

I wonder if we could get into trouble if some user has dozens or hundreds of items in the recycler and discovers that he can make them go away all at once. We don't offer this when we have sync access to local storage. Problems will be only worse for someone with long round-trip times and maybe limits on pending requests. I'd be ok with insisting that recycling be one item at a time.

I'd also be ok with saying that servers can be flexible with retention and maybe capping the number of items in the recycler at a dozen or two.

**Comment by paul90** [comment]
I did think about not having the 'Empty Recycler' - there are currently issues with it, but they almost certainly exist if somebody clicks on a lot of `x`'s quickly.

I will be replacing the use of emit to update the list - as this causes a server round trip which is best avoided.

Might be an idea to add a queue to limit the delete rate, and also change 'Empty Recycler' to empty the recycler directory in a single call.

I would like to avoid having any retention policy on the recycler, as that just makes it more complex.

**Comment by paul90** [comment]
With 092865f6668efa121d99e9bd7de406080874ec93 I have switched to having the delete from recycler processed in a queue. I have initially set concurrency to 2, so help limit the rate.

**Comment by WardCunningham** [comment]
Nice.

I agree a retention policy would be premature. Let's see the problem to be solved first. I'm having trouble thinking of any. We need not worry about abusive scenarios since the retained content comes from one source, the owner.
